name: CI

on: [push]

jobs:
  build-native-deb:
    runs-on: ubuntu-22.04
    container:
      image: debian:testing
    steps:
      - name: Installing Dependencies
        run: |
          apt update > /dev/null 2>&1
          apt install -y linux-image-amd64 linux-headers-amd64 debhelper-compat devscripts > /dev/null 2>&1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deb package
        run: |
          mk-build-deps --build-dep contrib/debian/control
          apt install -y ./*.deb
          sh autogen.sh
          ./configure
          cp -a contrib/debian debian
          sed 's/@CFGOPTS@/--enable-debuginfo/g' debian/rules.in > debian/rules
          chmod +x debian/rules
          dch -b -M --force-distribution --distribution bullseye-truenas-unstable 'Tagged from zfs CI'
          debuild -us -uc -b
          debian/rules override_dh_binary-modules

      - name: Create artifacts dir
        run: mkdir artifacts
        if: success()

      - name: Move artifacts
        run: mv ../*.deb artifacts
        if: success()

      - uses: actions/upload-artifact@v4
        with:
          name: zfs-native
          path: artifacts
        if: success()
